### ISSUE TITLE
Login/logout should know the method used

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-oauthclient#228] opened 2020-11-26 15:40 UTC
Currently, CERN contribs (and probably others) relies on signals to perform login/logout operations.
Unfortunately, all the contribs are "registered" on app init and they will all receive signals. 

### Problem

On login/logout, each contribs receive the signal and perform operations. The correct behaviour would be that only the contrib used to login should receive such signals.
This is also creating an issue on logout: given that `invenio-oauthclient` is not aware of which login method was used, the logout signal is emitted to all contribs and they all perform logout operations, causing issues in case of redirections.

### Possible solution

The solution could be to use DB information or add any extra information to store which was the authentication method used by the user. This could allow to stop firing signals to all contribs and emit only to the contrib used on login.

**Comment by GraemeWatt** [comment] 2021-05-25 10:09
For the HEPData service ([hepdata.net](https://www.hepdata.net)) we allow login with either CERN, ORCID, or local password, using the `invenio-oauthclient` package.  We've had an issue (HEPData/hepdata#106) for the last five years where if a user has previously connected to their CERN account, but uses one of the other methods (ORCID or local password) to log in, they get an exception `KeyError: 'Group'` from [this line](https://github.com/inveniosoftware/invenio-oauthclient/blob/2f4a4e60f595ab90fd60571dc49cc2d640cf806b/invenio_oauthclient/contrib/cern.py#L334) of [cern.py](https://github.com/inveniosoftware/invenio-oauthclient/blob/2f4a4e60f595ab90fd60571dc49cc2d640cf806b/invenio_oauthclient/contrib/cern.py).  We had hoped that this issue would be fixed in recent versions of `invenio-oauthclient` or when we moved to the new CERN SSO (merged PR HEPData/hepdata#343, but not yet deployed).  But we still get a similar exception `KeyError: 'cern_roles'` from [this line](https://github.com/inveniosoftware/invenio-oauthclient/blob/2f4a4e60f595ab90fd60571dc49cc2d640cf806b/invenio_oauthclient/contrib/cern_openid.py#L194) of [cern_openid.py](https://github.com/inveniosoftware/invenio-oauthclient/blob/2f4a4e60f595ab90fd60571dc49cc2d640cf806b/invenio_oauthclient/contrib/cern_openid.py).  These exceptions have generated complaints from HEPData users multiple times over the last five years.  Would you be able to prioritise fixing this issue for a future `invenio-oauthclient` release?

**Comment by ntarocco** [comment] 2021-05-25 10:16
@GraemeWatt thanks for reporting this. If you are moving to the more recent `cern_openid` then I would focus on that, and not on the old `cern.py`.
`cern_roles` should be there by default at CERN, I am surprised it is not the case.
Do you have access to the [CERN authentication documentation](https://auth.docs.cern.ch/user-documentation/oidc/config/#what-will-be-in-your-tokens)?
I am available to discuss this in the Discord chat.

**Comment by GraemeWatt** [comment] 2021-05-25 10:29
Thanks for the quick response, @ntarocco.  Yes, I can see these docs.  To clarify, the problem is not with CERN login itself.  It's with local (or ORCID) login where the CERN contrib still gets a signal according to this issue.  @alisonrclarke has investigated the problem in more detail.  We can discuss further in the `inveniosoftware` Discord chat if you prefer.

**Comment by ntarocco** [comment] 2021-05-25 12:36
It is clear now, thank you. I might have a solution (not ideal...), I will test it.

**Comment by ntarocco** [comment] 2021-05-25 15:58
> Thanks for the quick response, @ntarocco. Yes, I can see these docs. To clarify, the problem is not with CERN login itself. It's with local (or ORCID) login where the CERN contrib still gets a signal according to this issue. @alisonrclarke has investigated the problem in more detail. We can discuss further in the `inveniosoftware` Discord chat if you prefer.

See my PR: https://github.com/inveniosoftware/invenio-oauthclient/issues/228

**Closed** 2021-05-26 07:43 UTC
Labels: Type: bug

**Comment by ntarocco** [comment] 2021-05-26 12:28
@GraemeWatt `v1.5.1` released :)
